version: '3'
services:
  nginx:
    image: web # 这里需要替换成你的镜像名
    build:
      context: .
      dockerfile: .
    ports:
      - '80:80'
      - '443:443'
    # 环境变量
    #environment:
    #  -
    restart: unless-stopped
    volumes:
      - /home/nginx/cache:/var/cache/nginx
      - /home/nginx/ssl:/etc/nginx/ssl
      - /home/nginx/conf:/etc/nginx/conf
      - /home/nginx/log:/var/log/nginx
    container_name: nginx
